name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create the package
      run: dotnet pack --configuration Release
    - name: Publish BLL
      run: 
        dotnet nuget push BLL/bin/Release/*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
    - name: Publish DAL
      run: 
        dotnet nuget push DAL/bin/Release/*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
    - name: Publish Domain
      run: 
        dotnet nuget push Domain/bin/Release/*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
    - name: Publish Extensions
      run: 
        dotnet nuget push Extensions/bin/Release/*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
